
package webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2016-05-21T10:22:37.677+02:00
 * Generated source version: 2.7.14.redhat-1
 */

@WebFault(name = "LocalNotFoundError", targetNamespace = "http://webservices/")
public class LocalNotFoundError_Exception extends Exception {
    
    private webservices.LocalNotFoundError localNotFoundError;

    public LocalNotFoundError_Exception() {
        super();
    }
    
    public LocalNotFoundError_Exception(String message) {
        super(message);
    }
    
    public LocalNotFoundError_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public LocalNotFoundError_Exception(String message, webservices.LocalNotFoundError localNotFoundError) {
        super(message);
        this.localNotFoundError = localNotFoundError;
    }

    public LocalNotFoundError_Exception(String message, webservices.LocalNotFoundError localNotFoundError, Throwable cause) {
        super(message, cause);
        this.localNotFoundError = localNotFoundError;
    }

    public webservices.LocalNotFoundError getFaultInfo() {
        return this.localNotFoundError;
    }
}
