
package webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2016-05-21T10:22:37.602+02:00
 * Generated source version: 2.7.14.redhat-1
 */

@WebFault(name = "MissingSearchCriteriaError", targetNamespace = "http://webservices/")
public class MissingSearchCriteriaError_Exception extends Exception {
    
    private webservices.MissingSearchCriteriaError missingSearchCriteriaError;

    public MissingSearchCriteriaError_Exception() {
        super();
    }
    
    public MissingSearchCriteriaError_Exception(String message) {
        super(message);
    }
    
    public MissingSearchCriteriaError_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MissingSearchCriteriaError_Exception(String message, webservices.MissingSearchCriteriaError missingSearchCriteriaError) {
        super(message);
        this.missingSearchCriteriaError = missingSearchCriteriaError;
    }

    public MissingSearchCriteriaError_Exception(String message, webservices.MissingSearchCriteriaError missingSearchCriteriaError, Throwable cause) {
        super(message, cause);
        this.missingSearchCriteriaError = missingSearchCriteriaError;
    }

    public webservices.MissingSearchCriteriaError getFaultInfo() {
        return this.missingSearchCriteriaError;
    }
}
