
package webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2016-05-19T18:31:30.516+02:00
 * Generated source version: 2.7.14.redhat-1
 */

@WebFault(name = "WrongAccessibilityError", targetNamespace = "http://webservices/")
public class WrongAccessibilityError_Exception extends Exception {
    
    private webservices.WrongAccessibilityError wrongAccessibilityError;

    public WrongAccessibilityError_Exception() {
        super();
    }
    
    public WrongAccessibilityError_Exception(String message) {
        super(message);
    }
    
    public WrongAccessibilityError_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public WrongAccessibilityError_Exception(String message, webservices.WrongAccessibilityError wrongAccessibilityError) {
        super(message);
        this.wrongAccessibilityError = wrongAccessibilityError;
    }

    public WrongAccessibilityError_Exception(String message, webservices.WrongAccessibilityError wrongAccessibilityError, Throwable cause) {
        super(message, cause);
        this.wrongAccessibilityError = wrongAccessibilityError;
    }

    public webservices.WrongAccessibilityError getFaultInfo() {
        return this.wrongAccessibilityError;
    }
}
