
package webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2016-05-21T10:22:37.736+02:00
 * Generated source version: 2.7.14.redhat-1
 */

@WebFault(name = "WrongAddressError", targetNamespace = "http://webservices/")
public class WrongAddressError_Exception extends Exception {
    
    private webservices.WrongAddressError wrongAddressError;

    public WrongAddressError_Exception() {
        super();
    }
    
    public WrongAddressError_Exception(String message) {
        super(message);
    }
    
    public WrongAddressError_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public WrongAddressError_Exception(String message, webservices.WrongAddressError wrongAddressError) {
        super(message);
        this.wrongAddressError = wrongAddressError;
    }

    public WrongAddressError_Exception(String message, webservices.WrongAddressError wrongAddressError, Throwable cause) {
        super(message, cause);
        this.wrongAddressError = wrongAddressError;
    }

    public webservices.WrongAddressError getFaultInfo() {
        return this.wrongAddressError;
    }
}
